/// 证件照尺寸模板
class IdPhotoTemplate {
  final String id;
  final String name;
  final String nameEn;
  final double widthMm; // 宽度（毫米）
  final double heightMm; // 高度（毫米）
  final int widthPx; // 宽度（像素）
  final int heightPx; // 高度（像素）
  final int dpi; // 分辨率
  final String backgroundColor; // 背景颜色要求
  final int printCount; // 打印张数建议
  final String? country; // 国家/地区
  final bool isPremium; // 是否付费功能
  final List<String>? keywords; // 搜索关键词

  const IdPhotoTemplate({
    required this.id,
    required this.name,
    required this.nameEn,
    required this.widthMm,
    required this.heightMm,
    required this.widthPx,
    required this.heightPx,
    required this.dpi,
    required this.backgroundColor,
    required this.printCount,
    this.country,
    this.isPremium = false,
    this.keywords,
  });

  /// 获取宽高比
  double get aspectRatio => widthMm / heightMm;

  /// 转换为 Map（用于 Hive）
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'nameEn': nameEn,
      'widthMm': widthMm,
      'heightMm': heightMm,
      'widthPx': widthPx,
      'heightPx': heightPx,
      'dpi': dpi,
      'backgroundColor': backgroundColor,
      'printCount': printCount,
      'country': country,
      'isPremium': isPremium,
      'keywords': keywords,
    };
  }

  factory IdPhotoTemplate.fromMap(Map<String, dynamic> map) {
    return IdPhotoTemplate(
      id: map['id'] as String,
      name: map['name'] as String,
      nameEn: map['nameEn'] as String,
      widthMm: (map['widthMm'] as num).toDouble(),
      heightMm: (map['heightMm'] as num).toDouble(),
      widthPx: map['widthPx'] as int,
      heightPx: map['heightPx'] as int,
      dpi: map['dpi'] as int,
      backgroundColor: map['backgroundColor'] as String,
      printCount: map['printCount'] as int,
      country: map['country'] as String?,
      isPremium: map['isPremium'] as bool? ?? false,
      keywords: map['keywords'] != null
          ? List<String>.from(map['keywords'] as List)
          : null,
    );
  }

  /// 内置模板列表（扩展更多中国证件照尺寸）
  static List<IdPhotoTemplate> getDefaultTemplates() {
    return [
      // 中国证件照 - 基础尺寸
      const IdPhotoTemplate(
        id: 'china_1inch',
        name: '一寸',
        nameEn: '1 inch (China)',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['一寸', '1寸', '25x35'],
      ),
      const IdPhotoTemplate(
        id: 'china_2inch',
        name: '二寸',
        nameEn: '2 inch (China)',
        widthMm: 35,
        heightMm: 49,
        widthPx: 413,
        heightPx: 579,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 4,
        country: 'CN',
        keywords: ['二寸', '2寸', '35x49'],
      ),
      const IdPhotoTemplate(
        id: 'china_small_1inch',
        name: '小一寸',
        nameEn: 'Small 1 inch (China)',
        widthMm: 22,
        heightMm: 32,
        widthPx: 260,
        heightPx: 378,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 9,
        country: 'CN',
        keywords: ['小一寸', '小二寸'],
      ),
      const IdPhotoTemplate(
        id: 'china_large_1inch',
        name: '大一寸',
        nameEn: 'Large 1 inch (China)',
        widthMm: 33,
        heightMm: 48,
        widthPx: 390,
        heightPx: 567,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 4,
        country: 'CN',
        keywords: ['大一寸'],
      ),
      const IdPhotoTemplate(
        id: 'china_small_2inch',
        name: '小二寸',
        nameEn: 'Small 2 inch (China)',
        widthMm: 33,
        heightMm: 48,
        widthPx: 390,
        heightPx: 567,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 4,
        country: 'CN',
        keywords: ['小二寸'],
      ),

      // 中国证件照 - 考试类
      const IdPhotoTemplate(
        id: 'china_resume',
        name: '简历',
        nameEn: 'Resume',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['简历', '求职'],
      ),
      const IdPhotoTemplate(
        id: 'china_social_security',
        name: '社保',
        nameEn: 'Social Security',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 8,
        country: 'CN',
        keywords: ['社保', '社会保险'],
      ),
      const IdPhotoTemplate(
        id: 'china_mandarin',
        name: '普通话',
        nameEn: 'Mandarin Test',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色或蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['普通话', '普通话考试'],
      ),
      const IdPhotoTemplate(
        id: 'china_driver_license',
        name: '驾驶证',
        nameEn: 'Driver License',
        widthMm: 22,
        heightMm: 32,
        widthPx: 260,
        heightPx: 378,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 9,
        country: 'CN',
        keywords: ['驾驶证', '驾照', '广东驾驶证', '贵州驾驶证'],
      ),
      const IdPhotoTemplate(
        id: 'china_cet',
        name: '四六级',
        nameEn: 'CET-4/6',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['四六级', 'CET', '英语四级', '英语六级'],
      ),
      const IdPhotoTemplate(
        id: 'china_public_english',
        name: '公共英语',
        nameEn: 'Public English',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['公共英语', 'PETS'],
      ),
      const IdPhotoTemplate(
        id: 'china_teacher_qualification',
        name: '教师资格证',
        nameEn: 'Teacher Qualification',
        widthMm: 35,
        heightMm: 49,
        widthPx: 413,
        heightPx: 579,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'CN',
        keywords: ['教师资格证', '教师证'],
      ),
      const IdPhotoTemplate(
        id: 'china_nurse',
        name: '护士',
        nameEn: 'Nurse',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 8,
        country: 'CN',
        keywords: ['护士', '护士证'],
      ),
      const IdPhotoTemplate(
        id: 'china_adult_self_study',
        name: '成人自考',
        nameEn: 'Adult Self-Study',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['成人自考', '自考'],
      ),
      const IdPhotoTemplate(
        id: 'china_civil_service',
        name: '国考',
        nameEn: 'Civil Service Exam',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['国考', '公务员', '国家公务员'],
      ),
      const IdPhotoTemplate(
        id: 'china_gaokao',
        name: '高考报名',
        nameEn: 'Gaokao Registration',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['高考', '高考报名'],
      ),
      const IdPhotoTemplate(
        id: 'china_accounting',
        name: '会计',
        nameEn: 'Accounting',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['会计', '会计证'],
      ),
      const IdPhotoTemplate(
        id: 'china_computer',
        name: '计算机',
        nameEn: 'Computer',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '蓝色',
        printCount: 8,
        country: 'CN',
        keywords: ['计算机', '计算机等级'],
      ),
      const IdPhotoTemplate(
        id: 'china_id_card',
        name: '身份证',
        nameEn: 'ID Card',
        widthMm: 25,
        heightMm: 35,
        widthPx: 295,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 8,
        country: 'CN',
        keywords: ['身份证', '贵州身份证'],
      ),
      const IdPhotoTemplate(
        id: 'china_hk_macau_pass',
        name: '港澳通行证',
        nameEn: 'HK-Macau Pass',
        widthMm: 33,
        heightMm: 48,
        widthPx: 390,
        heightPx: 567,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'CN',
        keywords: ['港澳通行证', '港澳'],
      ),

      // 护照和签证
      const IdPhotoTemplate(
        id: 'passport',
        name: '护照',
        nameEn: 'Passport',
        widthMm: 33,
        heightMm: 48,
        widthPx: 390,
        heightPx: 567,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'CN',
        keywords: ['护照'],
      ),
      const IdPhotoTemplate(
        id: 'us_visa',
        name: '美国签证',
        nameEn: 'US Visa',
        widthMm: 50.8,
        heightMm: 50.8,
        widthPx: 600,
        heightPx: 600,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 2,
        country: 'US',
        keywords: ['美国签证', '美国', 'US'],
      ),
      const IdPhotoTemplate(
        id: 'japan_visa',
        name: '日本签证',
        nameEn: 'Japan Visa',
        widthMm: 45,
        heightMm: 35,
        widthPx: 531,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'JP',
        keywords: ['日本签证', '日本', 'Japan'],
      ),
      const IdPhotoTemplate(
        id: 'wedding_photo',
        name: '结婚照',
        nameEn: 'Wedding Photo',
        widthMm: 40,
        heightMm: 60,
        widthPx: 472,
        heightPx: 709,
        dpi: 300,
        backgroundColor: '红色',
        printCount: 4,
        country: 'CN',
        keywords: ['结婚照', '结婚证'],
      ),

      // 美国护照
      const IdPhotoTemplate(
        id: 'us_passport',
        name: '美国护照',
        nameEn: 'US Passport',
        widthMm: 50.8,
        heightMm: 50.8,
        widthPx: 600,
        heightPx: 600,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 2,
        country: 'US',
      ),
      // 日本证件照
      const IdPhotoTemplate(
        id: 'japan_resident',
        name: '日本在留卡',
        nameEn: 'Japan Resident Card',
        widthMm: 40,
        heightMm: 30,
        widthPx: 472,
        heightPx: 354,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'JP',
      ),
      const IdPhotoTemplate(
        id: 'japan_passport',
        name: '日本护照',
        nameEn: 'Japan Passport',
        widthMm: 45,
        heightMm: 35,
        widthPx: 531,
        heightPx: 413,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'JP',
      ),
      // 欧洲证件照
      const IdPhotoTemplate(
        id: 'eu_visa',
        name: '欧洲签证',
        nameEn: 'EU Visa',
        widthMm: 35,
        heightMm: 45,
        widthPx: 413,
        heightPx: 531,
        dpi: 300,
        backgroundColor: '白色',
        printCount: 4,
        country: 'EU',
      ),
    ];
  }
}
